#!/bin/sh
### BEGIN INIT INFO
# Provides:          logmonitor
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
start)
        start-stop-daemon --start --background --exec /etc/logmonitor/logmonitor.sh
	echo "apache log monitor...........[started]"
;;
stop)
        start-stop-daemon --stop --name logmonitor.sh
	echo "apache log monitor...........[stopped]"
esac
